use_frameworks!

target 'DSTPravitePod_Example' do
  pod 'DSTPravitePod', :path => '../'

  target 'DSTPravitePod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
